# Generated by Django 2.0.6 on 2020-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201203_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(max_length=256, upload_to='banner', verbose_name='轮播图片'),
        ),
    ]
